[package]
name = "rusty-ggml"
version = "0.0.2"
edition = "2021"

[dependencies]
ggml-sys-bleedingedge = "=2304290124.0.0"
anyhow = "1"
thiserror = "1"
num-traits = "0.2"
num-derive="0.3"
bytemuck = { version = "1", features = ["extern_crate_alloc"] }
